### ISSUE TITLE
Qualify the variable names in funktion.yml more

### ISSUE THREAD

**Issue by chirino** [redhat-ipaas/ipaas-rest#329]
seems like we could get in trouble if 2 components use a field named the same

```
---
flows:
- steps:
  - kind: endpoint
    uri: twitter-mention:?accessToken={{accessToken}}&accessTokenSecret={{accessTokenSecret}}&consumerKey={{consumerKey}}&consumerSecret={{consumerSecret}}
  - kind: endpoint
    uri: atlas:mapping-step-2.json
  - kind: endpoint
    uri: salesforce-upsert-contact:?clientId={{clientId}}&clientSecret={{clientSecret}}&loginUrl=https://login.salesforce.com&refreshToken={{refreshToken}}
```

instead of {{accessToken}} perhaps we should be using something like {{twitter-mention.accessToken}}
